package com.abstratsystems.kwasiadafrankaa.utils

import GameApiRequests
import Player
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory

object Instances {


    // The Retrofit Network library instance
    private val retrofit: Retrofit = Retrofit.Builder()
        .baseUrl("http://192.168.180.1:3000/api/")
        // Add a Gson converter factory to parse JSON responses
        .addConverterFactory(GsonConverterFactory.create())
        .build()

    // An Implementation of the OrgApiService interface is generated by Retrofit
    // for the making network requests
    val gameApiRequest: GameApiRequests = retrofit.create(GameApiRequests::class.java)
    // place holder for Player instances
    var player = Player("", "", "")
}